"""Turn one farm's replay into a replayable ghost opponent.

`opponents/` already holds ghosts of real rivals built this way. This makes one
of *our own* submissions, which is the only way to answer the question the
divergence raises: the ladder's 804-rated build exists only as a submission --
no source, none in this repo -- so the only way to play against it is to
replay the tape it actually produced.

    py -3.12 make_ghost.py replays/episode-95157730-replay.json \\
        --seat mine --out opponents/ghost_804.py

The tape is embedded in the file rather than loaded at runtime: the Kaggle
environment execs agent files without a usable `__file__`, so an `open()`
there fails silently and the agent degrades to PASS, which looks exactly like
a very bad opponent.

A ghost cannot react to us -- it plants and sells on the turns it originally
did, whatever we do -- so beating one is a counterfactual, not a head to head.
It is still the only available read on a build we cannot otherwise run.
"""
import argparse
import json
import os

ME = "Joseph Paris"

HEADER = '''"""Ghost of %s, seat %d of episode %s.

Replays the exact 720-turn action tape that farm played, so it cannot react to
us. Generated by make_ghost.py. Final bank in the original game: $%s.
"""
TAPE = %s


def agent(obs):
    step = obs.get("step")
    if step is None:
        step = obs["day"] * 24 + obs["hour"]
    if step < len(TAPE):
        return TAPE[step]
    return {"farmer": ["PASS"], "hands": [], "market": []}
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("replay")
    ap.add_argument("--seat", default="mine", choices=["mine", "theirs"])
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    with open(args.replay) as f:
        d = json.load(f)
    names = [a.get("Name") for a in d.get("info", {}).get("Agents", [])]
    mine = 0 if names and names[0] == ME else 1
    seat = mine if args.seat == "mine" else 1 - mine

    tape = []
    for step in d["steps"]:
        act = step[seat].get("action")
        if not isinstance(act, dict):
            act = {"farmer": ["PASS"], "hands": [], "market": []}
        tape.append({"farmer": act.get("farmer") or ["PASS"],
                     "hands": act.get("hands") or [],
                     "market": act.get("market") or []})

    reward = (d["steps"][-1][seat].get("reward") or 0)
    ep = os.path.basename(args.replay).split("-")[1]
    src = HEADER % (names[seat], seat, ep, format(int(reward), ","), repr(tape))
    with open(args.out, "w", newline="\r\n") as f:
        f.write(src)
    print("wrote %s  (%d turns, original bank $%s)"
          % (args.out, len(tape), format(int(reward), ",")))


if __name__ == "__main__":
    main()
